### ISSUE TITLE
Add optional sidecar to expose a http health check

### ISSUE THREAD

**Issue by bryopsida** [bryopsida/wireguard-chart#43]
In some cases it may be necessary to provide a health check to other services on the network, given that the wireguard protocol is UDP and does not provide a way to do this in the protocol itself. This will need to be done via a sidecar to expose a HTTP endpoint that can respond 200 when everything is functioning and 500 when not.

**Comment by lorenzomonta** [comment]
> In some cases it may be necessary to provide a health check to other services on the network, given that the wireguard protocol is UDP and does not provide a way to do this in the protocol itself. This will need to be done via a sidecar to expose a HTTP endpoint that can respond 200 when everything is functioning and 500 when not.

Is it possible to use something like [](http://node_ip:9586/metrics) ?

**Comment by lorenzomonta** [comment]
@bryopsida How could I "trick" it into working temporarily?

**Comment by bryopsida** [comment]
You could probably use the metrics end point if you switch the metrics service to a nodeport: 
https://github.com/bryopsida/wireguard-chart/blob/25e4c7eee8162b9de1693ec02f2e31e91fb8c8ff/helm/wireguard/templates/service-exporter.yaml#L17

**Comment by bryopsida** [comment]
> > In some cases it may be necessary to provide a health check to other services on the network, given that the wireguard protocol is UDP and does not provide a way to do this in the protocol itself. This will need to be done via a sidecar to expose a HTTP endpoint that can respond 200 when everything is functioning and 500 when not.
> 
> Is it possible to use something like http://node_ip:9586/metrics ?
> 
> But, the solution you provided is much cleaner. Is it complex to implement?

Not super complex but it involves making a new container image that can query the k8s API to get the overall status of the pod it's running in. This way the probe follows the status of the container. Once that container image is available the k8s manifest updates are fairly straight forward. I've started working on the image for the sidecar.

**Comment by bryopsida** [comment]
I'm working on the sidecar over here: https://github.com/bryopsida/http-healthcheck-sidecar

**Comment by bryopsida** [comment]
@lorenzomonta see if chart version 0.20.0 with the `healthSideCar`, does what you need.

If you are deploying as a deployment and using a node port service see: https://github.com/bryopsida/wireguard-chart/blob/main/ci/test-with-healthsidecar-nodeport.yaml and remove/adjust the `replicaCount` and `autoscaling` to suit your needs.

If you are deploying as a daemonset and using host ports see: https://github.com/bryopsida/wireguard-chart/blob/main/ci/test-with-healthsidecar-daemonset-hostport.yaml

Health endpoint will be available at your configured port, with `/health` path (other paths work but calling code will need to follow redirects).

Responds 200 if healthy, 503 if all containers on the pod aren't ready. Response body is just a plain text string aligning with the status codes.

**Comment by lorenzomonta** [comment]
@bryopsida Brilliant job, congratulations! You are a genius!
I tried both with /metrics as you suggested previously and /health and both work.
Now the vpn is up and running!
The only problem is that I can't viasuualize the data on Grafana, I see the dashboard but I don't see any data, I'm trying to figure out how why

**Comment by lorenzomonta** [comment]
For completeness, the health check can be automatically configured through the use of this annotation on the Oracle Cloud load balancer to become a network load balancer: **oci.oraclecloud.com/load-balancer-type: "nlb"**
So it is no longer necessary to expose the path /health @bryopsida 

`apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
  annotations:
    **oci.oraclecloud.com/load-balancer-type: "nlb"**
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx`
