### ISSUE TITLE
Wireguard vpn site to site

### ISSUE THREAD

**Issue by lorenzomonta** [bryopsida/wireguard-chart#47]
Is it possible to use wireguard with a site-to-site vpn setup?

**Comment by lorenzomonta** [comment]
I understand that architecturally having all the traffic from all the pods go out through the wiregurd pod instead of the node on which the pod resides may not make much sense
@bryopsida

**Comment by bryopsida** [comment]
I think there may be some overlap with this and: https://github.com/bryopsida/wireguard-chart/issues/38.

Is the other site also a kubernetes cluster? For cases like that leveraging something designed for cluster meshing may be the route you want to go.

- https://istio.io/latest/docs/setup/install/multicluster/
- https://docs.cilium.io/en/stable/network/clustermesh/intro/

Is the main goal to make cluster hosted services available to a LAN endpoints without needing to setup a wireguard tunnel for each client?

Or to expose something on the other site to pods in the cluster?

**Comment by lorenzomonta** [comment]
The goal is to do a site-to-site vpn between a firewall and the k8s cluster residing in the cloud. In my opinion at this point the best solution is to make an ipsec vpn between the cloud provider and the firewall so that it can reach to the k8s cluster.

Thank you for the ideas you provided me
