### ISSUE TITLE
Intermittent Connection

### ISSUE THREAD

**Issue by ALIP-0** [bryopsida/wireguard-chart#60]
Suffering intermittent connection, I have a 3 node cluster with a loadbalancer, when i set the replicaCount = 1 the connection becomes stable, any ideas what could be causing this? is it a loadbalancer issue or is it something else? I have seen issues like this in the past with other systems and the answer was to enable sticky sessions in the load balancer config ? Using Digital Ocean.

**Comment by bryopsida** [comment]
Have you tried enabling sticky sessions?

https://docs.digitalocean.com/glossary/sticky-session/#:~:text=Sticky%20session%2C%20or%20session%20persistence,that%20received%20the%20first%20request.

**Comment by ALIP-0** [comment]
Ill give it a try, i figured someone else would have come across this problem before now - can this be set in the helm chart ?

**Comment by bryopsida** [comment]
You should be able to set the annotations from the linked page with `service.annotations`

https://github.com/bryopsida/wireguard-chart/blob/60ceb2d21e245a046660523a20e2a162a52dc03e/helm/wireguard/templates/service.yaml#L8

IE
something like this.
``` yaml
service:
  annotations:
    annotation1: value1
```

Looking at the digital ocean docs it looks like that setting is specifically for http.

https://docs.digitalocean.com/glossary/udp/#load-balancer

This might be relevant though.
![image](https://github.com/user-attachments/assets/400a8744-82b6-41fc-8151-6ee7042e76d7)

What do you have set for your keep alive interval on your client side/tunnel config?

**Comment by bryopsida** [comment]
Try setting

`PersistentKeepalive = 25`

In your client/tunnel config, which will trigger a ping message from the client -> server every 25 seconds.

Also just confirming each pod is on its own node, or do you have multiple pods running on the same node?

**Comment by ALIP-0** [comment]
So i am working on an IoT project, each remote device transmits data every 1 second so i figured that a keep alive was not needed. Ill try it at 25.

I have a 3 node k8s cluster with 3 pods, one pod per node

**Comment by bryopsida** [comment]
> So i am working on an IoT project, each remote device transmits data every 1 second so i figured that a keep alive was not needed. Ill try it at 25.
> 
> I have a 3 node k8s cluster with 3 pods, one pod per node

Ah, with that traffic rate yeah, it should be keeping things active in the LB table. The keep alive may help with the clients detecting and re-handshaking quicker though.

Is there a pattern to when the connection drop occurs? Is it every so many minutes and the timing is predictable? Are there any kubernetes events that may be related, happening around the same time [kubectl events](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_events/) ?

**Comment by ALIP-0** [comment]
So most of my initial testing is using the windows client which i normally have good success with(i have another WG vpn configured that is 100%), once connected the connections seems good for at least a few seconds and sometimes a couple of minutes, once the connection dies i can disconnect and reconnect and it immediately works again, for a while. 

Enabling sticky sessions has not fixed the issue.

I might try with a older version of my values.yaml in case there is something wrong there

**Comment by ALIP-0** [comment]
Tried a few things and what i have discovered is that if i set the service type = NodePort i have a perfectly stable connection

**Comment by ALIP-0** [comment]
Just noticed this in loadbalancer the docs - does this suggest the need to use a lower MTU than 1420?

> When using UDP in forwarding rules, the maximum payload size of a UDP packet sent to the load balancer is 1424 bytes.

**Comment by bryopsida** [comment]
It seems like there is an implication that UDP load balancing uses forwarding rules in which case the MTU would need to be reduced so it can insert whatever headers it needs for forwarding into the packet.

![image](https://github.com/user-attachments/assets/61b9ecd9-4dc7-45a4-93a9-1e3d5546e500)

Does it stabilize if you drop your MTU?

**Comment by ALIP-0** [comment]
When defined as NodePort i am using one of the node external IPs as my endpoint, no loadbalancer configured anywhere.

Setting MTU down as far as 1280 on the client doesn't seem to make any difference, works initially then dies

**Comment by bryopsida** [comment]
> When defined as NodePort i am using one of the node external IPs as my endpoint, no loadbalancer configured anywhere.

That would be similar to running with one pod then, the digital ocean docs indicate that it looks at the source IP and pins that source IP to a droplet and the expected behavior is as long as the connection remains active for a minute and the droplet/node remains healthy, it should route the traffic to the same node/pod that the client initially handshaked with.

`
the load balancer assigns incoming connections to healthy target Droplets using the source IP of the client. This means that all subsequent requests from the same client land on the same target Droplet
`

I'm assuming that you are using the kubernetes LB and not setting up a UDP LB in digital ocean manually?

Are you using the health check side car to expose a health check?

https://github.com/bryopsida/wireguard-chart/blob/60ceb2d21e245a046660523a20e2a162a52dc03e/helm/wireguard/values.yaml#L271


And informing digital ocean how to setup the health checks for the LB on its end?
https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/

Digital oceans default behavior/configuration for setting up the health check may need to be adjusted.

![image](https://github.com/user-attachments/assets/4445806c-bea0-40b3-b872-0f62feb2e128)


Something like this.

``` yaml
healthSideCar:
  enabled: true
  service:
    type: NodePort
    nodePort: 31313
service:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "udp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port:  "31313"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
```

**Comment by ALIP-0** [comment]
Yes the helm chart is creating the loadbalancer, health check is true.

I have not been setting those annotations.

I have just tried and i get the error 

>  failed to build base load balancer request: specified health check port 31313 does not exist on service vpn/wg-vpn-wireguard

seems like its trying to find port 31313 on the vpn service rather than on the healthcheck service

**Comment by ALIP-0** [comment]
The issues remains but i have made progress, if a ping the wg address with the following the connection stays alive, without the ping -t the connection dies;

`ping 10.35.0.1 -t`


Loadbalancer config;

`annotations: {
    service.beta.kubernetes.io/do-loadbalancer-name: "vpn-loadbalancer", 
    service.beta.kubernetes.io/do-loadbalancer-override-health-check: "true",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "3000",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3",
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
  }`


Setting this to false prevents a separate service from being created;

`healthSideCar:
    service:
        enabled: false`

Adding an extra port to the vpn service allows the healthcheck to find the endpoint;

`extraPorts:
    - port: 3000
      name: http-monitoring`

Healthcheck sidecar log shows this now, updating every few seconds - looks like the loadbalancer is able to read the the endpoint ok ?

`2024/09/09 09:04:43.601425 k8s.go:45: [Info] Fetching status for pod %swg-vpn-wireguard-6cb9c6bdf8-c7mzj                                 2024/09/09 09:04:46.610155 k8s.go:45: [Info] Fetching status for pod %swg-vpn-wireguard-6cb9c6bdf8-c7mzj                                 2024/09/09 09:04:52.151305 k8s.go:45: [Info] Fetching status for pod %swg-vpn-wireguard-6cb9c6bdf8-c7mzj                                 2024/09/09 09:04:58.672085 k8s.go:45: [Info] Fetching status for pod %swg-vpn-wireguard-6cb9c6bdf8-c7mzj`

**Comment by bryopsida** [comment]
> Any thoughts or advice welcomed.

Docs for reference: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip, 

That seems like it might be the issue (Cluster traffic policy by default), according to the docs, setting that to local that would prevent allowing any additional hops to a different node inside the K8S network.

**Comment by ALIP-0** [comment]
Quick update to say that everything is still working well, i have left the settings as they are since the digital ocean console showed that it was trying to hit a healthcheck endpoint of http://0.0.0.0/healthz where as our actual healthcheck endpoint is /health

Just need to get the metrics working now in prometheus and ill be happy! i assume once metrics, servicemonitor and prometheusrule are all set to true that the defaults should allow prometheus to discover the exporter ?

**Comment by ALIP-0** [comment]
Final update, all working well.
